### ISSUE TITLE
Log -> Wood recipe gives one extra

### ISSUE THREAD

**Issue by anoomolu** [Fire-Horse27/azalea-wood#3]
Hiya! Lovely little mod, really like the textures too. It complements the vanilla woodsets well ^^

One quick thing - the azalea log -> wood recipe gives 4 rather than 3. Nothing a datapack can't fix, but just letting you know if you plan on updating any further :)

**Comment by Fire-Horse27** [comment]
Hey, thanks! I have a custom datapack that changes quite a few vanilla recipes to give more items. I forgot that others don't have that, so I'll make sure to update it to match vanilla sometime soon!
