### ISSUE TITLE
About 1.20.2+

### ISSUE THREAD

**Issue by vico93** [Fire-Horse27/azalea-wood#4]
Sorry about the question, but is there any updates for 1.20.2, 1.20.3 and 1.20.4 on the radar?

This mod is really useful!

**Comment by Fire-Horse27** [comment]
1.20.2 is already out! I might update if I have time for later versions. But they are not a priority right now. I will definitely update to 1.21 when that comes out.

I am glad you are enjoying the mod!

**Comment by vico93** [comment]
Just for information, the 1.20.2 version crashes in 1.20.4 with [this error](https://gist.github.com/vico93/50bf9ccace77bae2515245350f362605).

**Comment by vico93** [comment]
@DerpDerpling did a PR to an update to 1.20.4 at my request (on Fabric's Discord). In #6
