### ISSUE TITLE
Azalea logs inject themselves into bonus chest loot

### ISSUE THREAD

**Issue by anoomolu** [Fire-Horse27/azalea-wood#5]
Hiya! I've amended my issue, the original being in quotes. I had a look through the code, seems like https://github.com/Fire-Horse27/azalea-wood/blob/869c9e4f91a72c543ad79c7af8e85aafd554a181/src/main/java/net/firesteed/azaleawood/AzaleaWood.java#L37-L51 is responsible. Would it be possible to make this configurable/disable this feature? I'm not sure it's possible for players to spawn in a Lush Cave, and making Azalea wood available that early on doesn't seem right to me.

> Weird one - I've been messing with bonus chest loot for my superflat pack, and noticed that despite editing the vanilla spawn_bonus_chest loot table, these logs manage to sneak their way in. Using misode's loot table generator, it should be working as intended but it seems like these logs are replacing at least one of the item stacks in the chest.
> 
> For reference:
> ```
> {
>   "type": "minecraft:chest",
>   "pools": [
>     {
>       "rolls": 1,
>       "bonus_rolls": 0,
>       "entries": [
>         {
>           "type": "minecraft:item",
>           "name": "minecraft:dirt",
>           "functions": [
>             {
>               "function": "minecraft:set_count",
>               "count": 16
>         }]
>       }]
>     },
>     {
>       "rolls": 1,
>       "bonus_rolls": 0,
>       "entries": [
>         {
>           "type": "minecraft:item",
>           "name": "botania:living_root",
>           "functions": [
>             {
>               "function": "minecraft:set_count",
>               "count": 48
>         }]
>       }]
>     },
>     {
>       "rolls": 1,
>       "bonus_rolls": 0,
>       "entries": [
>         {
>           "type": "minecraft:item",
>           "name": "botania:grass_seeds",
>           "functions": [
>             {
>               "function": "minecraft:set_count",
>               "count": 1
>         }]
>       }]
>     },
>     {
>       "rolls": 1,
>       "bonus_rolls": 0,
>       "entries": [
>         {
>           "type": "minecraft:item",
>           "name": "minecraft:water_bucket",
>           "functions": [
>             {
>               "function": "minecraft:set_count",
>               "count": 1
>         }]
>       }]
>     }
>   ]
> }
> ```
> There's an inject elsewhere for the book from Botania, so here's how the loot should look (saplings, seeds and book placeholders for living root, grass seeds and botania book):
> ![image](https://github.com/Fire-Horse27/azalea-wood/assets/77850233/18220345-0d4b-49af-8f43-99141be0aba6)
> 
> However, this is what shows up in-game, suggesting that Azalea Wood might be doing a little something:
> ![image](https://github.com/Fire-Horse27/azalea-wood/assets/77850233/10fa3a94-84d0-4d68-91ea-63efb8e63b80)
> 
>

**Comment by Fire-Horse27** [comment]
This is my first mod, so I'm still figuring things out. I'm also currently very busy with school, so I am not currently planning on making this configurable. Sorry! I hope you could find a workaround to your problem. I'll definitely keep this in mind going into future updates though!

**Comment by Fire-Horse27** [comment]
From 1.20.3, the azalea wood will not be injected into bonus chests. Partly due to feedback, partly because it broke, and partly because I can't be bothered to fix it. ;D
